# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
---

    name: super-linter

    #
    # Documentation:
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions
    #

    on:
      pull_request:
        branches: [main]
      workflow_dispatch:

    permissions:
      contents: read
      packages: read
      statuses: write

    jobs:
      build:
        name: lint-codebase
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0 # Full git history is needed to get a proper list of changed files within `super-linter`

          - uses: github/super-linter/slim@v7 # use the slim linter since we don't use rust, dotenv, armttk, pwsh, or c#
            env:
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # The following linter types will be enabled:
              VALIDATE_BASH: true
              VALIDATE_BASH_EXEC: true
              VALIDATE_GITHUB_ACTIONS: true
              VALIDATE_JSON: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              VALIDATE_TERRAFORM_TFLINT: true
              VALIDATE_YAML: true
              FILTER_REGEX_EXCLUDE: ".github/dependabot.yml"
              
              # Additional settings:
              # If a shell script is not executable, the bash-exec
              # linter will report an error when set to true
              ERROR_ON_MISSING_EXEC_BIT: true

          # # Temporarily moving terrascan to a dedicated step with
          # # errors disabled. This is due to terrascan not yet
          # # supporting the GA release of optional() types.
          # - name: Run github/super-linter (terrascan only)
          #   uses: docker://github/super-linter:v4.9.7
          #   env:
          #     # Lint all code
          #     VALIDATE_ALL_CODEBASE: true
          #     # Need to define main branch as default
          #     # is set to master in super-linter
          #     DEFAULT_BRANCH: main
          #     # Enable setting the status of each individual linter
          #     # run in the Checks section of a pull request
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #     # The following linter types will be enabled:
          #     VALIDATE_TERRAFORM_TERRASCAN: true
          #     # Set linter to suppress errors
          #     # Enabled due to terrascan not yet supporting optional()
          #     # types in variables.
          #     DISABLE_ERRORS: true

